Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Module__c/Training_Module__c.object-meta.xml
<CustomObject>
    <label>Training Module</label>
    <nameField>
        <label>Training Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Module__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether completion is required</description>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

Employee training Project/force-app/main/default/classes/NotificationQuery.cls
public class NotificationQuery {
    Public Static CustomNotificationType getNotificationType(){
        return [SELECT Id FROM CustomNotificationType WHERE DeveloperName = 'Notification_to_Employee_from_Employee_Training' LIMIT 1];
    }
    Public Static List<Training_Module__c> getMapOfTrainingModule(String fieldName, Set<Id> temp){
       //Map<Id, Training_Module__c> returnMap = new Map<Id, Training_Module__c>(Database.query('SELECT Id, Mandatory__c FROM Training_Module__c WHERE Id IN :'TMIds);
       //return returnMap;
       return Database.query('SELECT Id, ' + fieldName + ' FROM Training_Module__c WHERE Id = :temp');
    }
}