Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <label>Employee Training</label>
    <nameField>
        <label>Employee Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>When training was completed</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee who completed the training</description>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Automatically calculated from module</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Upcoming</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Employee_Training__c/fields/Training_Module__c.field-meta.xml
<CustomField>
    <fullName>Training_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Module</label>
    <referenceTo>Training_Module__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Change_Log__c/Training_Change_Log__c.object-meta.xml
<CustomObject>
    <label>Training Change Log</label>
    <nameField>
        <label>Training Change Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Change_Log__c/fields/Employee_Training__c.field-meta.xml
<CustomField>
    <fullName>Employee_Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Training</label>
    <referenceTo>Employee_Training__c</referenceTo>
    <relationshipLabel>Training Change Logs</relationshipLabel>
    <relationshipName>Training_Change_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Module__c/Training_Module__c.object-meta.xml
<CustomObject>
    <label>Training Module</label>
    <nameField>
        <label>Training Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Module__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether completion is required</description>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

Interns-HUB/Training Compliance & Certification Tracking System Project/force-app/main/default/objects/Training_Module__c/fields/Validity_Period__c.field-meta.xml
<CustomField>
    <fullName>Validity_Period__c</fullName>
    <description>Number of months a certification is valid</description>
    <label>Validity Period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Employee training Project/force-app/main/default/classes/EmployeeTraininghandlerTest.cls
@isTest
public class EmployeeTraininghandlerTest {
    @testSetup
    static void setup(){
        Id systemAdminProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;

        User userExample = new User();
        userExample.Username = 'emailtest198@test.com';
        userExample.FirstName = 'First';
        userExample.LastName = 'Last';
        userExample.Alias = 'Alias';
        userExample.Email = 'emailtest@test.com';
        userExample.TimeZoneSidKey = 'America/New_York';
        userExample.LocaleSidKey = 'en_US';
        userExample.EmailEncodingKey = 'ISO-8859-1';
        userExample.ProfileId = systemAdminProfileId;
        userExample.LanguageLocaleKey = 'en_US';
        insert userExample;

        Training_Module__c testTms = new Training_Module__c(Name = 'Test Class Training Module', Mandatory__c = True, Validity_Period__c = 50);
        Insert testTms;
        
        Employee_Training__c testETs = new Employee_Training__c(Name = 'Test Class Employee Training', Completion_Date__c = Date.newInstance(2025, 7, 8), Employee__c = userExample.Id, Training_Module__c = testTms.Id, Status__c = 'Revoked');
        insert testETs;
        
        Employee_Training__c testETs2 = new Employee_Training__c(Name = 'Test Class Employee Training2', Completion_Date__c = Date.newInstance(2025, 7, 8), Employee__c = userExample.Id, Status__c = 'Completed');
        insert testETs2;
    }
    @isTest
    Public static void beforeInsertTest(){
        Employee_Training__c eT = [SELECT Id, Completion_Date__c, Expiry_Date__c, Training_Module__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        Training_Module__c tM = [SELECT Id, Validity_Period__c FROM Training_Module__c WHERE Id = :eT.Training_Module__c];
        Assert.areEqual(eT.Completion_Date__c.addDays(Integer.valueOf(tM.Validity_Period__c)), eT.Expiry_Date__c);
    }
    @isTest 
    Public static void afterInsertTest(){
        Employee_Training__c eT = [SELECT Id, Completion_Date__c, Expiry_Date__c, Training_Module__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        List<Training_Change_Log__c> tCL = [SELECT Id FROM Training_Change_Log__c WHERE Employee_Training__c = :eT.Id];
        Assert.areEqual(1,tCL.size());
    }
    @isTest
    Public static void beforeUpdateTest(){
        Employee_Training__c listOfETs = [SELECT Id, Completion_Date__c, Expiry_Date__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        
        Test.startTest();
        try{
        listOfETs.Expiry_Date__c = Date.newInstance(2025, 07, 08);
        update listOfETs;
        }catch (Exception e){
            Boolean exceptionThrown = (e.getMessage().contains('Cannot Update this record as it has finished its Expiry Date'))? true:false;
            Assert.areEqual(true, exceptionThrown, e.getMessage());
        }
        Test.stopTest();
        
        List<Training_Change_Log__c> tCL = [SELECT Id FROM Training_Change_Log__c WHERE Employee_Training__c = :listOfETs.Id];
        Assert.areEqual(1,tCL.size());
    }
    @isTest
    Public static void afterUpdateTest(){
        Employee_Training__c listOfETs = [SELECT Id, Completion_Date__c, Expiry_Date__c, Status__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        
        Test.startTest();
        listOfETs.Status__c = 'Expired';
        listOfETs.Expiry_Date__c = Date.newInstance(2025, 07, 12);
        Update listOfETs;
        Test.stopTest();
        
        List<Training_Change_Log__c> tCL = [SELECT Id FROM Training_Change_Log__c WHERE Employee_Training__c = :listOfETs.Id];
        Assert.areEqual(3,tCL.size());
    }
    @isTest
    Public static void beforeDeleteTest(){
        Employee_Training__c listOfETs = [SELECT Id, Completion_Date__c, Expiry_Date__c, Status__c, Training_Module__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        Test.startTest();
        try{
        Delete listOfETs;
        }catch (Exception e){
            Boolean exceptionThrown = (e.getMessage().contains('Cannot Delete this record as its related training module is mandatory'))? true : false;
            Assert.areEqual(true, exceptionThrown, e.getMessage());
        }
        Test.stopTest();

    }
    @isTest
    Public static void afterDeleteTest(){
        Employee_Training__c listOfETs = [SELECT Id, Completion_Date__c, Expiry_Date__c, Status__c, Training_Module__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training2' Limit 1];
        
        Test.startTest();
        delete listOfETs;
        Test.stopTest();
        
        List<Training_Change_Log__c> tCL = [SELECT Id FROM Training_Change_Log__c WHERE Employee_Training__c = :listOfETs.Id];
        Assert.areEqual(0,tCL.size());
    }
    @isTest
    Public static void afterUndeleteTest(){
        Training_Module__c listOfTMs = [SELECT Id, Mandatory__c FROM Training_Module__c WHERE Name = 'Test Class Training Module'];
        listOfTMs.Mandatory__c = False;
        Update listOfTMs;
        Employee_Training__c listOfETs = [SELECT Id, Completion_Date__c, Expiry_Date__c, Status__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' Limit 1];
        Delete listOfETs;
        Employee_Training__c listOfETs2 = [SELECT Id, Completion_Date__c, Expiry_Date__c, Status__c FROM Employee_Training__c WHERE Name = 'Test Class Employee Training' ALL ROWS];
        Undelete listOfETs2;
        List<Training_Change_Log__c> tCL = [SELECT Id FROM Training_Change_Log__c WHERE Employee_Training__c = :listOfETs2.Id];
        Assert.areEqual(2,tCL.size());
    }
}